<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_R</name>
   <tag></tag>
   <elementGuidId>dfaed37c-3280-4a87-8201-72ff0bafbabd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='p-avatar-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-avatar-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8bd085d1-a694-4e1a-b6f2-5449f8362b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-avatar-text</value>
      <webElementGuid>db610038-548f-49fc-a7ea-c679b8de9ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>R</value>
      <webElementGuid>0a6152d6-07ab-412b-ab6c-0c4c5e245da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;layout-wrapper screen layout-menu-light layout-topbar-blue layout-menu-static layout-menu-active&quot;]/div[@class=&quot;layout-topbar shadow-4&quot;]/div[@class=&quot;layout-topbar-right&quot;]/div[@class=&quot;layout-topbar-actions-right&quot;]/ul[@class=&quot;layout-topbar-items&quot;]/li[@class=&quot;layout-topbar-item&quot;]/a[@class=&quot;layout-topbar-action flex flex-row justify-content-center align-items-center px-2 rounded-circle p-ripple&quot;]/div[@class=&quot;p-avatar p-component p-avatar-circle&quot;]/span[@class=&quot;p-avatar-text&quot;]</value>
      <webElementGuid>545606c4-ee72-4306-a744-60894f78858d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/ul/li/a/div/span</value>
      <webElementGuid>563fb7ab-918b-437f-8ce1-a8e84bb25531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rio04'])[1]/preceding::span[2]</value>
      <webElementGuid>0536ce8d-846c-4001-9d6f-c457099e52e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SA'])[1]/preceding::span[3]</value>
      <webElementGuid>ec90e2b2-ab4b-4c76-9424-1605c93ffc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='R']/parent::*</value>
      <webElementGuid>e9d81a1b-c786-4dcc-b544-efb9355934f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>4999692c-3ce1-46e4-9366-d441a39b1698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'R' or . = 'R')]</value>
      <webElementGuid>b0e925ec-6557-4bb5-bfe2-316a17f7c1e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
